sources:
  - name: harmony-v3
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/aave/protocol-v3-harmony
        timeout: 5000 # 5 seconds
        retry: 2
    transforms:
      - blockTracking:
          # You might want to disable schema validation for faster startup
          validateSchema: false
