sources:
  - name: polygon-v2
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/aave/aave-v2-matic
        timeout: 5000 # 5 seconds
        retry: 2
    transforms:
      - blockTracking:
          # You might want to disable schema validation for faster startup
          validateSchema: false
